server:
  port: 8010

spring:
  application:
    name: DiscoveryService

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${server.port}/eureka/