spring:
  application:
    name: SPRING-SEC
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    root: debug

jwt:
  secret: bW9uZXlrZXlzLXJ1bGUtam90YS1zZWNyZXQtMTIzNDU2
  expiration: 3600000